      subroutine solomon
      write (*,*) 'Skipping Atmospheric Model'
      return
      end

c     subroutine effects
c     write (*,*) 'Skipping Effects Model'
c     return
c     end

c     subroutine calc_exposure_by_cohort
c     write (*,*) 'Skipping Cohort Vintaging'
c     return
c     end

c     subroutine read_exposure
c     return
c     end

      subroutine write_effects
      return
      end
