*========================================================================
*  ATM_RUN.BSL
*  Runfile for ozone maker model
*  Lines beginning with '*' are comments
*========================================================================
*--input data filenames:
*-------------------------------------
*--ODS species data--
   WMO2010.ODS
*
*-------------------------------------
*--filename: Emissions scenario--
   WMO2010_BSL.EMI
*-------------------------------------
